import type { Categorie } from "./types";

export const TITRES_PAR_CATEGORIE: Record<Categorie, string[]> = {
  anniversaire: [
    "La première fois qu'on s'est rencontrés",
    "Ce qui me fait sourire rien qu'en pensant à toi",
    "Le souvenir que je garde précieusement",
    "Ce que j'aurais voulu te dire depuis longtemps",
    "La chose que tu m'as apprise sans le savoir",
    "Mon moment préféré avec toi",
    "Ce que je te souhaite pour cette nouvelle année",
    "La fois où tu m'as surpris(e)",
    "Ce que j'admire le plus chez toi",
    "Tout ce qu'on va encore vivre ensemble",
  ],
  mariage: [
    "Le jour où j'ai su que vous étiez faits l'un pour l'autre",
    "Ce que j'aurais voulu dire pendant le discours",
    "Mon souvenir préféré de vous deux",
    "Ce que je vous souhaite pour cette nouvelle vie",
    "La première fois que je vous ai vus ensemble",
    "Ce que vous m'avez appris sur l'amour",
    "Un conseil pour les années à venir",
    "La chose qui me touche le plus chez vous deux",
    "Ce que je retiens de cette journée inoubliable",
    "Tout ce que je vous souhaite de vivre",
  ],
  retraite: [
    "Ce que tu as accompli et dont tu peux être fier(e)",
    "Mon souvenir préféré de notre temps ensemble",
    "Ce que tu m'as appris sans même t'en rendre compte",
    "La fois où tu m'as impressionné(e)",
    "Ce que je te souhaite pour cette nouvelle liberté",
    "Ce qui va nous manquer (et pas qu'un peu)",
    "Le meilleur conseil que tu m'aies jamais donné",
    "Ce que tu vas enfin pouvoir faire",
    "Une anecdote que je garderai toujours",
    "Tout ce qu'on te souhaite pour la suite",
  ],
  naissance: [
    "Le jour où on a appris la nouvelle",
    "Ce qu'on te souhaite pour ta vie",
    "Bienvenue dans notre famille",
    "Ce que tes parents t'ont déjà transmis",
    "Le monde dans lequel tu arrives",
    "Une promesse qu'on te fait",
    "Ce qu'on a hâte de te faire découvrir",
    "Tout l'amour qu'on a déjà pour toi",
    "La première chose qu'on veut te dire",
    "Ce que tu vas apporter dans nos vies",
  ],
  depart: [
    "Ce que tu laisses derrière toi",
    "Mon souvenir préféré de nous",
    "Ce qui va vraiment nous manquer",
    "Ce que tu m'as apporté sans le savoir",
    "Un conseil pour la route",
    "Ce que je te souhaite pour cette nouvelle aventure",
    "La fois où tu m'as rendu(e) fier(e)",
    "Ce qu'on gardera toujours de toi",
    "Tout ce qu'on espère pour toi là-bas",
    "À bientôt — et voilà pourquoi on y croit",
  ],
  autre: [
    "Ce que tu représentes pour moi",
    "Mon souvenir préféré avec toi",
    "Ce que je t'aurais dit si j'avais osé",
    "La chose que tu m'as apprise",
    "Ce que j'admire en toi",
    "Un moment qu'on ne pourra jamais oublier",
    "Ce que je te souhaite",
    "La fois où tu m'as surpris(e)",
    "Ce qui me fait penser à toi",
    "Tout ce que je voulais te dire",
  ],
};
